# Generated by Django 4.1.2 on 2023-04-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='weather_conditions',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
