# Generated by Django 4.1.2 on 2023-04-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_temperature_city_weather_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='city',
            name='weather_conditions',
            field=models.CharField(default='', max_length=255),
        ),
    ]
